source 'https://rubygems.org'

gem 'rails', '= 6.1.7.3'
gem 'chef', '~> 15', '>= 15.4.45'
gem 'jbuilder', '~> 1.5', '>= 1.5.3'
gem 'jquery-rails', '>= 4.4.0'
gem 'jwt' # For Zendesk SSO
gem 'rails_config', '~> 0.4.2'
gem 'rb-readline', '~> 0.5.2', require: false
gem 'sass-rails', '>= 6.0.0'
gem 'turbolinks', '~> 5.0.0'
gem 'unicorn-rails', '~> 1.1.0'
gem 'omniauth', '~> 2.1.0'
gem 'nokogiri', '>= 1.13.9'
gem 'pg'
gem 'mixlib-authentication', '~> 1.3'
gem 'sentry-raven'
gem 'responders', '~> 3.0', '>= 3.0.0'
gem 'newrelic_rpm'
gem 'doorkeeper', '~> 4.2.6'

gem 'veil', git: 'https://github.com/chef/chef_secrets'
gem 'omniauth-chef', git: 'https://github.com/chef/omniauth-chef'
gem 'chef-web-core', git: 'https://github.com/chef/chef-web-core.git'

#
# These gems require a javascript runtime.  We don't want to ship a
# javascript runtime so we put them in a separate group such that they
# don't get automatically required by rake.
#
group :node do
  gem 'coffee-rails', '~> 4.2.2'
  gem 'uglifier', '~> 2.7.2'
end

group :development, :test do
  # Loading it this way makes it work with Ruby 2.1.2. See
  # https://github.com/nixme/jazz_hands/issues/25
  gem 'jazz_hands', git: 'https://github.com/nixme/jazz_hands', branch: 'bring-your-own-debugger'
  gem 'pry-byebug'
  gem 'mailcatcher'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.1'
end

group :development do
  gem 'better_errors', '>= 2.8.0'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'spring' # App preloading
  gem 'spring-commands-rspec'
  gem 'thor', '~> 0.18.0'
end

group :doc do
  gem 'sdoc', '>= 1.0.0', require: false
end

group :test do
  gem 'capybara', '~> 2.4.4'
  gem 'factory_girl_rails', '~> 4.4.1'
  gem 'selenium-webdriver', '2.38.0'
  gem 'timecop'
end
